SymEdit\Bundle\MediaBundle\Model\Media:
    properties:
        name:
            - NotBlank:
                groups: [require_name]
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"

SymEdit\Bundle\MediaBundle\Model\Image:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: path
    properties:
        file:
            - Image:
                groups: [require_name, image_only]
                maxSize: 20M

SymEdit\Bundle\MediaBundle\Model\File:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: path
    properties:
        file:
            - File:
                maxSize: 200M
