SymEdit\Bundle\MediaBundle\Model\Image:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: path
    properties:
        name:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"
        file:
            - Image:
                maxSize: 20M

SymEdit\Bundle\MediaBundle\Model\File:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: path
    properties:
        name:
            - NotBlank: ~
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"
        file:
            - File:
                maxSize: 200M