SymEdit\Bundle\MediaBundle\Model\GalleryItem:
    type: entity
    table: gallery_item
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        image:
            targetEntity: SymEdit\Bundle\MediaBundle\Model\ImageInterface
            joinColumn:
                name: image_id
                referencedColumnName: id
                onDelete: CASCADE
            cascade:
                - persist
        gallery:
            targetEntity: SymEdit\Bundle\MediaBundle\Model\ImageGalleryInterface
            inversedBy: galleryItems
