SymEdit\Bundle\MediaBundle\Model\ImageGallery:
    type: entity
    table: image_gallery
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        title:
            type: string
            length: 255
        slug:
            type: string
            unique: true
            nullable: false
            gedmo:
                slug:
                    unique: true
                    separator: "-"
                    fields:
                        - title
    oneToMany:
        items:
            mappedBy: gallery
            targetEntity: SymEdit\Bundle\MediaBundle\Model\GalleryItemInterface
            orderBy:
                position: ASC
            cascade:
                - persist
                - remove
