SymEdit\Bundle\MediaBundle\Model\Media:
    type: entity
    table: media
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
        length: 10
    discriminatorMap:
        image: SymEdit\Bundle\MediaBundle\Model\Image
        file: SymEdit\Bundle\MediaBundle\Model\File
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: string
            length: 255
            unique: true
        name:
            type: string
            length: 255
        updatedAt:
            type: datetime
