SymEdit\Bundle\MediaBundle\Model\Media:
    exclusion_policy: ALL
    xml_root_name: media
    properties:
        id:
            expose: true
        path:
            expose: true
        name:
            expose: true
        updatedAt:
            expose: true
